import {Brain,Network,Workflow,TrendingUp,MessageCircle,GraduationCap,Baby,Users,Wifi,Leaf,ShieldCheck,BarChart3,Mail,Phone,Globe2,ArrowRight,Handshake} from 'lucide-react';
const products=[
 ['Talker','Communication, messaging, video & conference calls',MessageCircle],
 ['Scholar Solver AI','AI assistance for university students',GraduationCap],
 ['EduKids','Interactive education for children',Baby],
 ['Smiley','Social networking and digital communities',Users],
 ['Strata','Digital data vending and connectivity services',Wifi],
 ['Farm Hub AI','AI-powered tools for farmers',Leaf]
];
const pillars=[['AI First','Intelligence built into every product.',Brain],['Connected Ecosystem','Products designed to work together.',Network],['Automation','Reduce repetitive work through intelligent systems.',Workflow],['Scalable Technology','Built to grow from local to international markets.',TrendingUp]];
export default function Home(){return <div className="min-h-screen bg-[#020817] text-white overflow-hidden">
<header className="sticky top-0 z-50 bg-[#020817]/90 backdrop-blur-xl border-b border-cyan-400/10"><div className="max-w-7xl mx-auto px-5 h-20 flex items-center justify-between"><a href="#home" className="flex items-center gap-3"><img src="/vynorqa-logo.jpeg" className="h-14 w-14 rounded-xl object-cover"/><b className="text-2xl">Vynorqa</b></a><nav className="hidden lg:flex gap-7 text-sm text-slate-300"><a href="#about">About</a><a href="#technology">AI Technology</a><a href="#products">Products</a><a href="#innovation">Innovation</a><a href="#partnerships">Partnerships</a><a href="#contact">Contact</a></nav><a href="#contact" className="neo-btn">Get in Touch</a></div></header>
<section id="home" className="relative min-h-[720px] flex items-center"><img src="/vynorqa-hero.png" className="absolute inset-0 w-full h-full object-cover opacity-40"/><div className="absolute inset-0 bg-gradient-to-r from-[#020817] via-[#020817]/80 to-[#020817]/25"/><div className="relative max-w-7xl mx-auto px-5 py-24 w-full"><div className="max-w-2xl"><p className="eyebrow">Innovation today • A smarter tomorrow</p><h1 className="text-6xl md:text-8xl font-black tracking-tight">Vynorqa</h1><h2 className="text-3xl md:text-5xl font-bold mt-4 leading-tight">Building intelligent technology for a <span className="gradient-text">connected future.</span></h2><p className="text-lg text-slate-300 mt-6 max-w-xl">AI-powered digital products solving real-world challenges in communication, education, social platforms, agriculture and digital services across Africa and beyond.</p><div className="flex flex-wrap gap-4 mt-8"><a href="#technology" className="neo-btn">Explore Our Technology <ArrowRight size={17}/></a><a href="#products" className="outline-btn">Our Products <ArrowRight size={17}/></a></div></div></div></section>
<section id="about" className="section"><div className="max-w-7xl mx-auto px-5 grid lg:grid-cols-2 gap-12 items-center"><div><p className="eyebrow">About Vynorqa</p><h2 className="heading">Technology built around <span className="gradient-text">real human needs.</span></h2></div><p className="copy">Vynorqa develops AI-powered digital products designed to solve problems in communication, education, social platforms, agriculture and digital services. Our ecosystem connects intelligent tools with practical everyday experiences for people, businesses and communities.</p></div></section>
<section id="technology" className="section bg-[#050d22]"><div className="max-w-7xl mx-auto px-5"><p className="eyebrow">Vynorqa AI Core</p><h2 className="heading">One intelligence layer. <span className="gradient-text">Six powerful capabilities.</span></h2><div className="grid sm:grid-cols-2 lg:grid-cols-6 gap-4 mt-10">{[['Intelligence',Brain],['Automation',Workflow],['Personalization',Users],['Analytics',BarChart3],['Security',ShieldCheck],['Business Operations',TrendingUp]].map(([t,I]:any)=><div className="glass-card text-center" key={t}><I className="mx-auto text-cyan-300"/><b className="block mt-4">{t}</b></div>)}</div></div></section>
<section id="products" className="section"><div className="max-w-7xl mx-auto px-5"><p className="eyebrow">Product ecosystem</p><h2 className="heading">One company. <span className="gradient-text">Multiple intelligent solutions.</span></h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 mt-10">{products.map(([t,d,I]:any)=><article className="glass-card product-card" key={t}><div className="icon-orb"><I/></div><h3 className="text-2xl font-bold mt-5">{t}</h3><p className="text-slate-400 mt-2">{d}</p><span className="inline-flex items-center gap-2 mt-6 text-cyan-300 font-semibold">Discover product <ArrowRight size={16}/></span></article>)}</div></div></section>
<section className="section bg-[#050d22]"><div className="max-w-7xl mx-auto px-5"><p className="eyebrow">Why Vynorqa</p><div className="grid lg:grid-cols-4 gap-5 mt-8">{pillars.map(([t,d,I]:any)=><div className="glass-card" key={t}><I className="text-fuchsia-400"/><h3 className="text-xl font-bold mt-4">{t}</h3><p className="text-slate-400 mt-2">{d}</p></div>)}</div></div></section>
<section className="section"><div className="max-w-7xl mx-auto px-5 grid lg:grid-cols-2 gap-12 items-center"><div className="rounded-3xl min-h-[390px] bg-gradient-to-br from-cyan-500/20 via-blue-700/10 to-fuchsia-500/20 border border-cyan-300/20 grid place-items-center p-10"><div className="text-center"><Brain size={76} className="mx-auto text-cyan-300"/><p className="eyebrow mt-6">Founder / Vision</p><p className="text-2xl md:text-3xl font-semibold leading-relaxed">“We are building technology that doesn't simply respond to people — it understands what they need and helps them get it done.”</p></div></div><div><p className="eyebrow">Our Vision</p><h2 className="heading">African innovation with <span className="gradient-text">global ambition.</span></h2><p className="copy">Vynorqa is creating a connected technology ecosystem that can scale with the people and markets it serves. The founder portrait can be added here once supplied.</p></div></div></section>
<section id="innovation" className="section bg-[#050d22]"><div className="max-w-7xl mx-auto px-5"><p className="eyebrow">Vynorqa AI Command Center</p><h2 className="heading">See the ecosystem <span className="gradient-text">as one intelligent operation.</span></h2><div className="command mt-10"><div className="text-center"><Brain size={45} className="mx-auto text-cyan-300"/><b className="text-2xl block mt-2">Vynorqa AI Core</b></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3 mt-8">{products.map(([t])=><div className="mini" key={t}>{t}</div>)}</div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-8">{['Users','Revenue','System Health','AI Activity','Customer Support','Product Analytics','Payments','Security Alerts'].map(x=><div className="metric" key={x}><span className="text-slate-400 text-xs">{x}</span><b className="block mt-1 text-cyan-300">Live</b></div>)}</div></div></div></section>
<section id="partnerships" className="section"><div className="max-w-5xl mx-auto px-5 text-center"><Handshake size={48} className="mx-auto text-fuchsia-400"/><p className="eyebrow mt-5">Partnerships</p><h2 className="heading">Let's build the <span className="gradient-text">future together.</span></h2><div className="flex flex-wrap justify-center gap-3 mt-7"><a href="mailto:info@vynorqa.co.zw" className="neo-btn">Partner with Vynorqa</a><a href="mailto:info@vynorqa.co.zw" className="outline-btn">Business Enquiries</a><a href="mailto:info@vynorqa.co.zw" className="outline-btn">Technology Partnerships</a></div></div></section>
<section id="contact" className="section bg-[#050d22]"><div className="max-w-7xl mx-auto px-5 grid lg:grid-cols-2 gap-10"><div><p className="eyebrow">Contact</p><h2 className="heading">Start a conversation.</h2><div className="space-y-4 text-slate-300"><a className="contact" href="tel:+263714907480"><Phone/> +263 714 907 480</a><a className="contact" href="mailto:info@vynorqa.co.zw"><Mail/> info@vynorqa.co.zw</a><a className="contact" href="https://www.vynorqa.co.zw"><Globe2/> www.vynorqa.co.zw</a></div></div><form className="glass-card grid gap-4" onSubmit={e=>e.preventDefault()}><input className="field" placeholder="Your name"/><input className="field" type="email" placeholder="Email address"/><select className="field"><option>Business enquiry</option><option>Partnership</option><option>Technology partnership</option><option>Product enquiry</option></select><textarea className="field min-h-32" placeholder="Tell us how we can help"/><button className="neo-btn justify-center">Send Enquiry</button></form></div></section>
<footer className="border-t border-cyan-300/10 py-10"><div className="max-w-7xl mx-auto px-5 flex flex-col md:flex-row gap-5 justify-between"><div><b className="text-2xl">VYNORQA</b><p className="text-slate-400">Intelligence. Innovation. Impact.</p></div><p className="text-slate-500">Products | About | Technology | Partnerships | Contact<br/>© 2026 Vynorqa. All rights reserved.</p></div></footer>
<a href="https://wa.me/263714907480?text=Hi%20Vynorqa%2C%20I%20would%20like%20to%20find%20out%20more." target="_blank" rel="noreferrer" className="fixed right-5 bottom-5 z-50 w-14 h-14 rounded-full bg-green-500 grid place-items-center shadow-2xl"><MessageCircle/></a>
</div>}
