import {useEffect,useState} from 'react';
import {Brain,Network,Workflow,TrendingUp,MessageCircle,GraduationCap,Baby,Users,Wifi,Leaf,ShieldCheck,BarChart3,Mail,Phone,Globe2,ArrowRight,Handshake,Video,ChevronRight} from 'lucide-react';
import FloatingWhatsApp from '../components/FloatingWhatsApp';

const products=[
 {id:'talker',name:'Talker',desc:'Communication, messaging, video & conference calls',Icon:MessageCircle},
 {id:'scholar',name:'Scholar Solver AI',desc:'AI assistance for university students',Icon:GraduationCap},
 {id:'edukids',name:'EduKids',desc:'Interactive education for children',Icon:Baby},
 {id:'smiley',name:'Smiley',desc:'Social networking and digital communities',Icon:Users},
 {id:'strata',name:'Strata',desc:'Digital data vending and connectivity services',Icon:Wifi},
 {id:'farmhub',name:'Farm Hub AI',desc:'AI-powered tools for farmers',Icon:Leaf}
];
const pillars=[['AI First','Intelligence built into every product.',Brain],['Connected Ecosystem','Products designed to work together.',Network],['Automation','Reduce repetitive work through intelligent systems.',Workflow],['Scalable Technology','Built to grow from local to international markets.',TrendingUp]];

function Typewriter({text,speed=34}:{text:string,speed?:number}){const[out,setOut]=useState('');useEffect(()=>{setOut('');let i=0;const id=setInterval(()=>{i++;setOut(text.slice(0,i));if(i>=text.length)clearInterval(id)},speed);return()=>clearInterval(id)},[text,speed]);return <>{out}<span className="typing-cursor"/></>}

export default function Home(){return <div className="min-h-screen bg-[#020817] text-white overflow-hidden">
<header className="sticky top-0 z-50 bg-[#020817]/90 backdrop-blur-xl border-b border-cyan-400/10"><div className="max-w-7xl mx-auto px-5 h-20 flex items-center justify-between"><a href="#home" className="flex items-center gap-3"><img src="/vynorqa-logo.jpeg" className="h-14 w-14 rounded-xl object-cover"/><div><b className="text-2xl">Vynorqa</b><div className="text-[9px] tracking-[.22em] text-slate-400 uppercase">Innovation today • A smarter tomorrow</div></div></a><nav className="hidden lg:flex gap-7 text-sm text-slate-300"><a href="#home">Home</a><a href="#about">About</a><a href="#technology">AI Technology</a><a href="#products">Products</a><a href="#innovation">Innovation</a><a href="#partnerships">Partnerships</a><a href="#contact">Contact</a></nav><a href="#contact" className="neo-btn">Get in Touch</a></div></header>

<section id="home" className="relative min-h-[760px] flex items-center border-b border-cyan-400/10">
<div className="absolute inset-0 overflow-hidden">
  <div className="absolute -top-24 -right-20 h-[560px] w-[560px] rounded-full bg-cyan-500/20 blur-3xl"/>
  <div className="absolute top-32 right-32 h-[420px] w-[420px] rounded-full bg-blue-600/20 blur-3xl"/>
  <div className="absolute bottom-10 right-0 h-[380px] w-[380px] rounded-full bg-fuchsia-600/20 blur-3xl"/>
  <div className="absolute inset-0 opacity-40" style={{backgroundImage:'radial-gradient(circle at 70% 38%, rgba(35,214,255,.22) 0, rgba(35,214,255,0) 32%), linear-gradient(rgba(255,255,255,.035) 1px, transparent 1px), linear-gradient(90deg,rgba(255,255,255,.035) 1px, transparent 1px)',backgroundSize:'auto, 42px 42px, 42px 42px'}}/>
</div>
<div className="absolute inset-0 bg-gradient-to-r from-[#020817] via-[#020817]/78 to-[#020817]/18"/>
<div className="relative max-w-7xl mx-auto px-5 py-24 w-full grid lg:grid-cols-[1.05fr_.95fr] gap-10 items-center">
<div className="max-w-2xl"><p className="eyebrow">Innovation today • A smarter tomorrow</p><h1 className="text-6xl md:text-8xl font-black tracking-tight">Vynorqa</h1>
<h2 className="text-3xl md:text-5xl font-bold mt-4 leading-tight min-h-[116px]"><Typewriter text="Building intelligent technology for a connected future."/></h2>
<p className="text-lg text-slate-300 mt-6 max-w-xl min-h-[92px]"><Typewriter text="AI-powered digital products solving real-world challenges in communication, education, social platforms, agriculture and digital services across Africa and beyond." speed={18}/></p>
<div className="flex flex-wrap gap-4 mt-8"><a href="#technology" className="neo-btn">Explore Our Technology <ArrowRight size={17}/></a><a href="#products" className="outline-btn">Our Products <ArrowRight size={17}/></a></div>
<div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-10 text-sm text-slate-300"><div>🧠 AI Powered Solutions</div><div>🌍 Built for Africa & Beyond</div><div>👥 People Focused</div><div>📈 A Smarter Tomorrow</div></div></div>
<div className="relative hidden lg:block h-[520px]">
<div className="absolute inset-0 rounded-full border border-cyan-300/20 shadow-[0_0_80px_rgba(26,213,255,.15)]"/>
{products.map((p,i)=>{const pos=[[8,22],[65,8],[76,40],[66,70],[8,67],[-1,45]][i];return <a href={'#product-'+p.id} key={p.id} className="hero-product" style={{left:pos[0]+'%',top:pos[1]+'%',animationDelay:(i*.23)+'s'}}><p.Icon size={24}/><span>{p.name}</span></a>})}
<div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 glass-card !p-8 text-center shadow-[0_0_55px_rgba(92,99,255,.35)]"><Brain className="mx-auto text-cyan-300" size={46}/><b className="block mt-3 text-xl">Vynorqa AI Core</b><span className="text-xs text-slate-400">Connecting people, ideas & opportunities</span></div>
</div></div></section>

<section className="py-12 md:py-16 bg-[#030a1b] border-b border-cyan-400/10">
  <div className="max-w-7xl mx-auto px-5">
    <div className="rounded-[28px] overflow-hidden border border-cyan-300/15 bg-[#061127] shadow-2xl">
      <img src="/vynorqa-hero.png" alt="Vynorqa connected AI ecosystem visual" className="w-full h-auto block"/>
    </div>
  </div>
</section>

<section id="products" className="section bg-[#040b1c]"><div className="max-w-7xl mx-auto px-5"><div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6"><div><p className="eyebrow">Our products</p><h2 className="heading">An Ecosystem for a <span className="gradient-text">Smarter Tomorrow</span></h2></div><p className="text-slate-400 max-w-xl">Six powerful products. One intelligent ecosystem. Transforming lives through technology.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 mt-10">{products.map((p,i)=><article id={'product-'+p.id} className="glass-card product-card scroll-mt-28" key={p.name}><div className="icon-orb animate-float" style={{animationDelay:(i*.18)+'s'}}><p.Icon/></div><h3 className="text-2xl font-bold mt-5">{p.name}</h3><p className="text-slate-400 mt-2">{p.desc}</p><a href="#contact" className="inline-flex items-center gap-2 mt-6 text-cyan-300 font-semibold">Enquire about {p.name}<ChevronRight size={16}/></a></article>)}</div></div></section>

<section id="about" className="section"><div className="max-w-7xl mx-auto px-5 grid lg:grid-cols-2 gap-12 items-center"><div><p className="eyebrow">About Vynorqa</p><h2 className="heading">Technology built around <span className="gradient-text">real human needs.</span></h2></div><p className="copy">Vynorqa develops AI-powered digital products designed to solve problems in communication, education, social platforms, agriculture and digital services. Our ecosystem connects intelligent tools with practical everyday experiences for people, businesses and communities.</p></div></section>

<section id="technology" className="section bg-[#050d22]"><div className="max-w-7xl mx-auto px-5"><p className="eyebrow">Vynorqa AI Core</p><h2 className="heading">One intelligence layer. <span className="gradient-text">Six powerful capabilities.</span></h2><div className="grid sm:grid-cols-2 lg:grid-cols-6 gap-4 mt-10">{[['Intelligence',Brain],['Automation',Workflow],['Personalization',Users],['Analytics',BarChart3],['Security',ShieldCheck],['Business Operations',TrendingUp]].map(([t,I]:any,i)=><a href="#innovation" className="glass-card text-center product-card" key={t}><I className="mx-auto text-cyan-300 animate-float" style={{animationDelay:(i*.15)+'s'}}/><b className="block mt-4">{t}</b></a>)}</div></div></section>

<section className="section"><div className="max-w-7xl mx-auto px-5"><p className="eyebrow">Why Vynorqa</p><div className="grid lg:grid-cols-4 gap-5 mt-8">{pillars.map(([t,d,I]:any,i)=><div className="glass-card" key={t}><I className="text-fuchsia-400 animate-float" style={{animationDelay:(i*.18)+'s'}}/><h3 className="text-xl font-bold mt-4">{t}</h3><p className="text-slate-400 mt-2">{d}</p></div>)}</div></div></section>

<section className="section bg-[#050d22]"><div className="max-w-7xl mx-auto px-5 grid lg:grid-cols-2 gap-12 items-center"><div className="rounded-3xl min-h-[390px] bg-gradient-to-br from-cyan-500/20 via-blue-700/10 to-fuchsia-500/20 border border-cyan-300/20 grid place-items-center p-10"><div className="text-center"><Brain size={76} className="mx-auto text-cyan-300"/><p className="eyebrow mt-6">Founder / Vision</p><p className="text-2xl md:text-3xl font-semibold leading-relaxed">“We are building technology that doesn't simply respond to people — it understands what they need and helps them get it done.”</p></div></div><div><p className="eyebrow">Our Vision</p><h2 className="heading">African innovation with <span className="gradient-text">global ambition.</span></h2><p className="copy">Vynorqa is creating a connected technology ecosystem that can scale with the people and markets it serves. The founder portrait can be added here once supplied.</p></div></div></section>

<section id="innovation" className="section"><div className="max-w-7xl mx-auto px-5"><p className="eyebrow">Vynorqa AI Command Center</p><h2 className="heading">See the ecosystem <span className="gradient-text">as one intelligent operation.</span></h2><div className="command mt-10"><div className="text-center"><Brain size={45} className="mx-auto text-cyan-300 animate-float"/><b className="text-2xl block mt-2">Vynorqa AI Core</b></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3 mt-8">{products.map(p=><a href={'#product-'+p.id} className="mini" key={p.name}>{p.name}</a>)}</div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-8">{['Users','Revenue','System Health','AI Activity','Customer Support','Product Analytics','Payments','Security Alerts'].map(x=><div className="metric" key={x}><span className="text-slate-400 text-xs">{x}</span><b className="block mt-1 text-cyan-300">Live</b></div>)}</div></div></div></section>

<section id="partnerships" className="section bg-[#050d22]"><div className="max-w-5xl mx-auto px-5 text-center"><Handshake size={48} className="mx-auto text-fuchsia-400"/><p className="eyebrow mt-5">Partnerships</p><h2 className="heading">Let's build the <span className="gradient-text">future together.</span></h2><div className="flex flex-wrap justify-center gap-3 mt-7"><a href="mailto:info@vynorqa.co.zw?subject=Partner%20with%20Vynorqa" className="neo-btn">Partner with Vynorqa</a><a href="mailto:info@vynorqa.co.zw?subject=Business%20Enquiry" className="outline-btn">Business Enquiries</a><a href="mailto:info@vynorqa.co.zw?subject=Technology%20Partnership" className="outline-btn">Technology Partnerships</a></div></div></section>

<section id="contact" className="section"><div className="max-w-7xl mx-auto px-5 grid lg:grid-cols-2 gap-10"><div><p className="eyebrow">Contact</p><h2 className="heading">Start a conversation.</h2><div className="space-y-4 text-slate-300"><a className="contact" href="tel:+263714907480"><Phone/> +263 714 907 480</a><a className="contact" href="mailto:info@vynorqa.co.zw"><Mail/> info@vynorqa.co.zw</a><a className="contact" href="https://www.vynorqa.co.zw" target="_blank" rel="noreferrer"><Globe2/> www.vynorqa.co.zw</a></div></div><form className="glass-card grid gap-4" onSubmit={e=>{e.preventDefault();window.location.href='mailto:info@vynorqa.co.zw?subject=Website%20Enquiry'}}><input className="field" placeholder="Your name" required/><input className="field" type="email" placeholder="Email address" required/><select className="field"><option>Business enquiry</option><option>Partnership</option><option>Technology partnership</option><option>Product enquiry</option></select><textarea className="field min-h-32" placeholder="Tell us how we can help" required/><button className="neo-btn justify-center">Send Enquiry</button></form></div></section>
<footer className="border-t border-cyan-300/10 py-10"><div className="max-w-7xl mx-auto px-5 flex flex-col md:flex-row gap-5 justify-between"><div><b className="text-2xl">VYNORQA</b><p className="text-slate-400">Intelligence. Innovation. Impact.</p></div><p className="text-slate-500"><a href="#products">Products</a> | <a href="#about">About</a> | <a href="#technology">Technology</a> | <a href="#partnerships">Partnerships</a> | <a href="#contact">Contact</a><br/>© 2026 Vynorqa. All rights reserved.</p></div></footer>
<FloatingWhatsApp/>
</div>}