import { useMemo, useState } from 'react';
import { MessageCircle, X, ArrowLeft, Send, CheckCircle2 } from 'lucide-react';
type Step = 'welcome' | 'name' | 'phone' | 'service' | 'message' | 'review';
const SERVICES = ['Talker','Scholar Solver AI','EduKids','Smiley','Strata','Farm Hub AI','Business Partnership','Technology Partnership','General Enquiry'];
const WHATSAPP_NUMBER = '263714907480';
const BUSINESS_NAME = 'Vynorqa';
export default function FloatingWhatsApp() {
  const [open, setOpen] = useState(false); const [step, setStep] = useState<Step>('welcome');
  const [data, setData] = useState({ name: '', phone: '', service: '', message: '' });
  const canContinue = useMemo(() => step==='name'?data.name.trim().length>1:step==='phone'?data.phone.trim().length>6:step==='service'?!!data.service:step==='message'?data.message.trim().length>2:true,[step,data]);
  const order:Step[]=['welcome','name','phone','service','message','review'];
  const next=()=>setStep(order[Math.min(order.indexOf(step)+1,order.length-1)]);
  const back=()=>setStep(order[Math.max(order.indexOf(step)-1,0)]);
  const sendToWhatsApp=()=>{const text=`Hi Vynorqa, I would like assistance.%0A%0AName: ${encodeURIComponent(data.name)}%0APhone: ${encodeURIComponent(data.phone)}%0AService: ${encodeURIComponent(data.service)}%0AMessage: ${encodeURIComponent(data.message)}`;window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${text}`,'_blank','noopener,noreferrer');setOpen(false)};
  return <div className="fixed bottom-[76px] right-4 z-50 md:bottom-8">{open&&<div className="animate-chat-slide mb-3 w-[calc(100vw-2rem)] max-w-[370px] overflow-hidden rounded-3xl border border-cyan-300/15 bg-[#061127] shadow-2xl"><div className="bg-gradient-to-r from-cyan-500/20 via-blue-600/20 to-fuchsia-600/20 px-5 py-4 text-white"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-green-500"><MessageCircle size={20}/></div><div><p className="font-bold">Vynorqa AI Assistant</p><p className="text-xs text-slate-300">Online • Ready to help</p></div></div><button onClick={()=>setOpen(false)} className="rounded-full p-2 hover:bg-white/10"><X size={18}/></button></div></div><div className="min-h-[300px] p-5 text-white">
  {step==='welcome'&&<><Bubble>Hi 👋 Welcome to Vynorqa. I can help you with our products, partnerships or a general enquiry.</Bubble><Bubble>I’ll collect a few details and then prepare your WhatsApp message.</Bubble></>}
  {step==='name'&&<Field label="What's your name?" value={data.name} onChange={v=>setData({...data,name:v})} placeholder="Your full name"/>}
  {step==='phone'&&<Field label={`Thanks ${data.name}. What's your phone number?`} value={data.phone} onChange={v=>setData({...data,phone:v})} placeholder="+263 ..." type="tel"/>}
  {step==='service'&&<div><p className="mb-3 text-sm font-semibold">What are you interested in?</p><div className="grid gap-2 max-h-60 overflow-y-auto">{SERVICES.map(s=><button key={s} onClick={()=>setData({...data,service:s})} className={`rounded-xl border px-4 py-3 text-left text-sm transition ${data.service===s?'border-cyan-300 bg-cyan-300/10 text-cyan-200':'border-white/10 hover:border-cyan-300/40'}`}>{s}</button>)}</div></div>}
  {step==='message'&&<div><p className="mb-3 text-sm font-semibold">Tell us briefly what you need.</p><textarea rows={5} value={data.message} onChange={e=>setData({...data,message:e.target.value})} placeholder="Your enquiry..." className="w-full resize-none rounded-xl border border-white/10 bg-[#020817] p-3 text-sm outline-none focus:border-cyan-300"/></div>}
  {step==='review'&&<div><div className="mb-4 flex items-center gap-2 text-green-400"><CheckCircle2 size={20}/><b>Ready to send</b></div><div className="space-y-2 rounded-2xl bg-white/5 p-4 text-sm"><p><b>Name:</b> {data.name}</p><p><b>Phone:</b> {data.phone}</p><p><b>Service:</b> {data.service}</p><p><b>Message:</b> {data.message}</p></div><p className="mt-3 text-xs text-slate-400">Nothing is sent until you press “Continue on WhatsApp”.</p></div>}
</div><div className="flex items-center gap-2 border-t border-white/10 p-4">{step!=='welcome'&&<button onClick={back} className="flex h-11 w-11 items-center justify-center rounded-xl border border-white/10"><ArrowLeft size={17}/></button>}{step!=='review'?<button onClick={next} disabled={!canContinue} className="flex-1 rounded-xl bg-gradient-to-r from-cyan-500 via-blue-600 to-fuchsia-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-40">{step==='welcome'?'Start Chat':'Continue'}</button>:<button onClick={sendToWhatsApp} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-green-600 px-4 py-3 text-sm font-bold text-white"><Send size={16}/> Continue on WhatsApp</button>}</div></div>}<button onClick={()=>setOpen(!open)} aria-label="Open Vynorqa assistant" className="animate-pulse-gold flex h-14 w-14 items-center justify-center rounded-full bg-green-500 text-white shadow-2xl transition hover:-translate-y-1">{open?<X size={27}/>:<MessageCircle size={29}/>}</button></div>}
function Bubble({children}:{children:React.ReactNode}){return <div className="mb-3 max-w-[92%] rounded-2xl rounded-tl-sm bg-white/8 px-4 py-3 text-sm leading-relaxed text-slate-200">{children}</div>}
function Field({label,value,onChange,placeholder,type='text'}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;type?:string}){return <div><p className="mb-3 text-sm font-semibold">{label}</p><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-white/10 bg-[#020817] px-4 py-3 text-sm outline-none focus:border-cyan-300"/></div>}